version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./pdfs:/app/pdfs
      - ./models:/app/models
    environment:
      - NODE_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend